name: atheneum-connector

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      TYPE: FORGE
      MODRINTH_PROJECTS: kotlin-for-forge
    volumes:
      - data:/data
      - ./build/libs:/mods

volumes:
  data: